sitecorelabs/xmcloud-foundation-head-dev

src/sxastarter/package-lock.json, src/sxastarter/package.json
Upgrade to JSS 21.0.2 packages
=> Upgrade to JSS 21.0.2 packages

src/sxastarter/package.json, src/sxastarter/src/temp/GraphQLIntrospectionResult.json
JSS 21.0.2 updates to the starter (missed with previous #45)
=> JSS 21.0.2 starter updates

src/sxastarter/src/assets/basic/_header.scss
Fixed header styles.
Problem was in position of two or many components on the one row. This fix also fix for default headless site header styles in preview(normal) mode.
=>  #552985: [SXA] fixed header styles

src/sxastarter/src/assets/sass/components/_component-container.scss
This changes need to fix showing hidden components
Problem was with not correct style for each component when we use function **Hidden components** in EE
=>  #546298: [SXA]fixed style for showing hidden components

src/sxastarter/package-lock.json, src/sxastarter/package.json
updated sitecore-jss-* packages till 21.0.4 stable version. This version fixed dynamic placeholders
=>  #559044: fixed dynamic placeholders

src/sxastarter/src/components/FEaaSWrapper.tsx
FEaaSWrapper component has been implemented
=>  #565348 FEaaSWrapper component has been implemented

src/sxastarter/src/components/play-travel/PageCard.tsx
PageCard component has been implemented
=>  #569714 PageCard component has been implemented

src/sxastarter/src/components/play-travel/Experiences.tsx
Experiences component has been modified
=>  #570108 Experiences component has been modified

src/sxastarter/src/assets/play-travel/_features.scss, src/sxastarter/src/assets/play-travel/index.scss, src/sxastarter/src/components/play-travel/Features.tsx
Features component has been implemented
=>  #548389 Features component has been implemented

src/sxastarter/src/components/play-travel/Experiences.tsx, src/sxastarter/src/components/play-travel/PageCard.tsx
Add href property for the PageCard component
=>  #569714 Add href property for the PageCard component

src/sxastarter/src/components/play-travel/Partners.tsx
Partners component has been implemented
=>  #570585 Partners component has been implemented

src/sxastarter/src/components/Container.tsx, src/sxastarter/tailwind.config.js
upgrade tailwind config and added class `flex-wrap` for Container
=>  #569573: upgrade tailwind config

src/sxastarter/package.json, src/sxastarter/src/assets/play-travel/_contact-form.scss, src/sxastarter/src/assets/play-travel/index.scss, src/sxastarter/src/components/play-travel/ContactForm.tsx
Contact form has been implemented
=>  #573717 Contact form has been implemented

src/sxastarter/src/assets/play-travel/_menu.scss, src/sxastarter/src/assets/play-travel/index.scss, src/sxastarter/src/components/play-travel/Accordion.tsx, src/sxastarter/src/components/play-travel/Experiences.tsx, src/sxastarter/src/components/play-travel/Features.tsx, src/sxastarter/src/components/play-travel/Hero.tsx, src/sxastarter/src/components/play-travel/Link.tsx, src/sxastarter/src/components/play-travel/Menu.tsx, src/sxastarter/src/components/play-travel/PageCard.tsx, src/sxastarter/src/components/play-travel/Slots.tsx
Menu component has been implemented
=>  #548379 Menu component has been implemented

src/sxastarter/src/assets/play-travel/_teaser.scss, src/sxastarter/src/components/play-travel/Wrapper.tsx
Fix background image for Wrapper
=>  #576626 Fix background image for Wrapper

docker-compose.override.yml, docker-compose.yml, up.ps1
- Version removed from docker-compose.yml
- Scale replaced with deploy.replicas in docker-compose.override.yml
- "docker-compose" command replaced with "docker compose"
=> #589662 Upgrade to Docker compose V2

src/sxastarter/package-lock.json, src/sxastarter/package.json
Update to latest @sitecore-feaas/clientside version 0.3.6
=> Update to latest @sitecore-feaas/clientside

src/sxastarter/package-lock.json, src/sxastarter/package.json, src/sxastarter/src/lib/middleware/plugins/redirects.ts, src/sxastarter/src/middleware.ts
Hotfix released in JSS 21.2.3
https://github.com/Sitecore/jss/pull/1566
=> [JSS 21.2.3][sitecore-jss-nexjts] Redirects don't work when file extensions present in a route

src/sxastarter/package-lock.json, src/sxastarter/package.json
The package-lock got corrupted while downgrading the nextjs version.
Regenerated it to fix the build issue.
=> Regenerate package-lock

src/renderinghost.module.json
=> Fix wrong rendering host schema path

src/sxastarter/package-lock.json, src/sxastarter/package.json, src/sxastarter/src/assets/sass/_app.scss, src/sxastarter/src/assets/sass/abstracts/_mixins.scss, src/sxastarter/src/assets/sass/components/_component-container.scss, src/sxastarter/src/components/CdpPageView.tsx
Reverts sitecorelabs/xmcloud-foundation-head-dev#150
=> Revert "JSS: Upgrade to v21.5.0"

src/sxastarter/README.md, src/sxastarter/package-lock.json, src/sxastarter/package.json, src/sxastarter/scripts/config/plugins/multisite.ts, src/sxastarter/scripts/generate-config.ts, src/sxastarter/src/pages/api/robots.ts, src/sxastarter/src/pages/api/sitemap.ts
Updated sxastarter to use JSS 22.0.0
=> [JSS] Updated sxastarter to v22.0.0
